In [1]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns
import os
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [2]:
pd.set_option('display.max_columns', None)
final_depression = pd.read_csv('data_train_depr.csv')
final_anxiety = pd.read_csv('data_train_anx.csv')
final_stress = pd.read_csv('data_train_str.csv')

display(final_depression, final_anxiety, final_stress)

Q3A  Q5A  Q10A  Q13A  Q16A  Q17A  Q21A  Q24A  Q26A  Q31A  Q34A  Q37A  \
0        0    0     0     0     0     1     1     0     0     0     1     0   
1        1    1     1     1     2     1     1     1     2     1     1     1   
2        1    2     0     2     3     3     2     3     2     2     3     0   
3        0    0     0     0     2     0     0     1     1     0     0     0   
4        1    2     1     1     1     2     2     0     2     1     1     1   
...    ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
16795    1    3     2     3     1     3     1     3     2     2     3     2   
16796    2    3     3     2     2     0     1     3     2     2     0     3   
16797    1    2     2     2     1     2     2     2     3     2     1     0   
16798    3    3     3     3     3     3     3     3     3     3     3     3   
16799    0    3     3     3     2     2     2     1     0     1     2     2   

       Q38A  Q42A  Extraverted-enthusiastic  Critical-quarrelsome  \
0         0     2                         5                     2   
1         1     1                         0                     0   
2         2     3                         5                     6   
3         0     0                         7                     3   
4         0     3                         2                     3   
...     ...   ...                       ...                   ...   
16795     1     2                         1                     2   
16796     1     3                         7                     2   
16797     2     2                         4                     1   
16798     3     3                         2                     5   
16799     2     0                         6                     1   

       Dependable-self_disciplined  Anxious-easily upset  \
0                                2                     3   
1                                0                     1   
2                                6                     5   
3                                2                     3   
4                                2                     3   
...                            ...                   ...   
16795                            1                     6   
16796                            5                     6   
16797                            7                     7   
16798                            2                     7   
16799                            6                     7   

       Open to new experiences-complex  Reserved-quiet  Sympathetic-warm  \
0                                    6               3                 7   
1                                    0               2                 0   
2                                    7               2                 3   
3                                    5               3                 6   
4                                    3               2                 2   
...                                ...             ...               ...   
16795                                3               7                 5   
16796                                4               3                 2   
16797                                5               7                 7   
16798                                5               5                 6   
16799                                5               5                 7   

       Disorganized-careless  Calm-emotionally_stable  \
0                          7                        6   
1                          5                        0   
2                          4                        2   
3                          5                        4   
4                          3                        1   
...                      ...                      ...   
16795                      3                        2   
16796                      6                        2   
16797                      1                        5   
16798                    

Q2A  Q4A  Q7A  Q9A  Q15A  Q19A  Q20A  Q23A  Q25A  Q28A  Q30A  Q36A  \
0        3    1    2    1     0     0     1     1     3     1     0     0   
1        3    0    0    1     0     1     0     0     2     1     1     0   
2        1    1    1    2     0     1     1     1     1     1     1     2   
3        0    0    0    0     0     0     0     0     0     0     0     0   
4        3    1    0    2     0     0     3     0     1     0     3     3   
...    ...  ...  ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   
16795    0    1    2    3     0     1     2     0     0     0     1     0   
16796    3    1    3    3     0     1     3     0     3     3     1     1   
16797    2    2    1    1     1     1     1     0     0     2     2     2   
16798    3    2    3    3     1     3     1     0     0     2     3     1   
16799    0    1    1    2     0     0     2     0     3     1     3     1   

       Q40A  Q41A  Extraverted-enthusiastic  Critical-quarrelsome  \
0         2     0                         4                     3   
1         3     0                         1                     6   
2         1     1                         6                     5   
3         0     0                         5                     4   
4         3     3                         1                     7   
...     ...   ...                       ...                   ...   
16795     2     2                         3                     3   
16796     3     1                         5                     7   
16797     1     1                         4                     5   
16798     3     2                         6                     7   
16799     3     0                         5                     1   

       Dependable-self_disciplined  Anxious-easily upset  \
0                                5                     5   
1                                4                     7   
2                                7                     5   
3                                6                     1   
4                                1                     7   
...                            ...                   ...   
16795                            6                     6   
16796                            4                     7   
16797                            7                     7   
16798                            5                     7   
16799                            6                     7   

       Open to new experiences-complex  Reserved-quiet  Sympathetic-warm  \
0                                    6               6                 3   
1                                    2               6                 4   
2                                    5               6                 5   
3                                    6               5                 3   
4                                    1               7                 4   
...                                ...             ...               ...   
16795                                5               6                 7   
16796                                7               7                 7   
16797                                4               6                 6   
16798                                6               5                 5   
16799                                7               7                 6   

       Disorganized-careless  Calm-emotionally_stable  \
0                          5                        2   
1                          4                        2   
2                          4                        6   
3                          1                        6   
4                          7                        1   
...                      ...                      ...   
16795                      2                        4   
16796                      1                        4   
16797                      6                        4   
16798                      4                     

Q1A  Q6A  Q8A  Q11A  Q12A  Q14A  Q18A  Q22A  Q27A  Q29A  Q32A  Q33A  \
0        2    3    3     2     2     2     2     1     3     2     2     2   
1        2    3    3     3     1     1     1     2     2     3     1     1   
2        1    1    2     1     1     0     1     0     1     3     0     1   
3        1    1    2     1     1     1     1     1     1     1     1     1   
4        0    1    1     1     3     0     3     2     1     2     2     2   
...    ...  ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
16795    1    0    1     1     2     2     1     1     1     2     0     2   
16796    1    0    0     1     0     2     1     0     2     1     1     1   
16797    1    2    3     1     2     1     2     0     2     0     0     2   
16798    0    1    1     1     1     2     1     2     1     0     0     2   
16799    1    1    1     1     0     1     1     0     1     1     1     0   

       Q35A  Q39A  Extraverted-enthusiastic  Critical-quarrelsome  \
0         2     3                         4                     5   
1         1     1                         6                     5   
2         0     1                         1                     1   
3         0     1                         6                     4   
4         3     2                         1                     6   
...     ...   ...                       ...                   ...   
16795     1     1                         3                     2   
16796     1     1                         1                     5   
16797     0     1                         4                     1   
16798     0     2                         4                     5   
16799     1     1                         6                     7   

       Dependable-self_disciplined  Anxious-easily upset  \
0                                7                     6   
1                                3                     6   
2                                7                     5   
3                                5                     3   
4                                5                     5   
...                            ...                   ...   
16795                            3                     7   
16796                            6                     2   
16797                            5                     5   
16798                            5                     5   
16799                            7                     5   

       Open to new experiences-complex  Reserved-quiet  Sympathetic-warm  \
0                                    6               7                 7   
1                                    6               1                 5   
2                                    4               7                 6   
3                                    3               2                 7   
4                                    1               7                 1   
...                                ...             ...               ...   
16795                                7               6                 6   
16796                                7               5                 6   
16797                                5               7                 2   
16798                                3               6                 5   
16799                                6               5                 7   

       Disorganized-careless  Calm-emotionally_stable  \
0                          5                        7   
1                          6                        2   
2                          5                        5   
3                          1                        7   
4                          2                        1   
...                      ...                      ...   
16795                      6                        3   
16796                      2                        5   
16797                      4                        2   
16798                      4         

In [3]:
X_Depression = final_depression.iloc[:,0:14].values
y_Depression = final_depression.iloc[:,-1:].values

X_Anxiety = final_anxiety.iloc[:,0:14].values
y_Anxiety = final_anxiety.iloc[:,-1:].values

X_Stress = final_stress.iloc[:,0:14].values
y_Stress = final_stress.iloc[:,-1:].values

print(X_Depression)
print(y_Depression)

print(X_Anxiety)
print(y_Anxiety)

print(X_Stress)
print(y_Stress)

[[0 0 0 ... 1 4 3]
 [1 1 1 ... 1 5 2]
 [1 2 0 ... 1 5 2]
 ...
 [1 2 2 ... 1 5 3]
 [3 3 3 ... 1 4 2]
 [0 3 3 ... 1 4 2]]
[[0]
 [1]
 [2]
 ...
 [2]
 [2]
 [2]]
[[3 1 2 ... 1 3 2]
 [3 0 0 ... 2 4 3]
 [1 1 1 ... 1 2 3]
 ...
 [2 2 1 ... 1 5 2]
 [3 2 3 ... 1 5 3]
 [0 1 1 ... 1 3 2]]
[[1]
 [0]
 [1]
 ...
 [1]
 [2]
 [1]]
[[2 3 3 ... 1 3 3]
 [2 3 3 ... 1 2 2]
 [1 1 2 ... 2 2 4]
 ...
 [1 2 3 ... 1 2 3]
 [0 1 1 ... 1 0 2]
 [1 1 1 ... 2 1 3]]
[[2]
 [2]
 [0]
 ...
 [1]
 [1]
 [0]]


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing

scaler=MinMaxScaler()

X_train_depression, X_test_depression, y_train_depression, y_test_depression = train_test_split(X_Depression, y_Depression, test_size=0.3, random_state=0)
X_train_anxiety, X_test_anxiety, y_train_anxiety, y_test_anxiety = train_test_split(X_Anxiety, y_Anxiety, test_size=0.3, random_state=0)
X_train_stress, X_test_stress, y_train_stress, y_test_stress = train_test_split(X_Stress, y_Stress, test_size=0.3, random_state=0)

X_train_depression = scaler.fit_transform(X_train_depression)
X_test_depression = scaler.transform(X_test_depression)
X_train_anxiety = scaler.fit_transform(X_train_anxiety)
X_test_anxiety = scaler.transform(X_test_anxiety)
X_train_stress = scaler.fit_transform(X_train_stress)
X_test_stress = scaler.transform(X_test_stress)

print(y_train_depression.shape,y_test_depression.shape,X_train_depression.shape,X_test_depression.shape)
print(y_train_anxiety.shape,y_test_anxiety.shape,X_train_anxiety.shape,X_test_anxiety.shape)
print(y_train_stress.shape,y_test_stress.shape,X_train_stress.shape,X_test_stress.shape)

(11760, 1) (5040, 1) (11760, 54) (5040, 54)
(11760, 1) (5040, 1) (11760, 54) (5040, 54)
(11760, 1) (5040, 1) (11760, 54) (5040, 54)


In [6]:
def build_model(train_data, label_data):
    model = tf.keras.Sequential([
      #tf.keras.layers.Flatten(input_shape=(14,)),
      tf.keras.layers.Dense(512, activation = 'relu',input_shape=(14,), name ="Input"), #input_shape=[15]
      #tf.keras.layers.Dense(256, activation='relu'),
      #tf.keras.layers.Dense(256, activation='relu'),
      tf.keras.layers.Dense(256, activation='relu'),
      #tf.keras.layers.Dense(64, activation='relu'),
      #tf.keras.layers.Dense(7, activation='softmax', name="layer3")
      tf.keras.layers.Dense(3, activation='softmax', name="Condition")
    ])

    model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),     #SparseCategoricalCrossentropy
              metrics=['accuracy'])

    model.fit(X_train_depression, y_train_depression, batch_size=32, epochs=20)

    return model

In [7]:
model_dep  = build_model(X_train_depression, y_train_depression)
model_anx = build_model(X_train_anxiety, y_train_anxiety)
model_str = build_model1(X_train_stress, y_train_stress)
# model_dep = historydep.to_json()
# with open('historydep.json', 'w') as json_file:
#     json_file.write(model_dep)

# historyanx = model.fit(X_train_anxiety, y_train_anxiety, batch_size=32, epochs=100)
# model_anx = historyanx.to_json()
# with open('historyanx.json', 'w') as json_file:
#     json_file.write(model_anx)

# historystr = model.fit(X_train_stress, y_train_stress, batch_size=32, epochs=100)
# model_str = historystr.to_json()
# with open('historyanx.json', 'w') as json_file:
#     json_file.write(model_anx)


Epoch 1/20


d:\Python\lib\site-packages\tensorflow\python\util\dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


368/368 [==============================] - 2s 4ms/step - loss: 0.1861 - accuracy: 0.9254
Epoch 2/20
368/368 [==============================] - 2s 4ms/step - loss: 0.1043 - accuracy: 0.9565
Epoch 3/20
368/368 [==============================] - 1s 4ms/step - loss: 0.0807 - accuracy: 0.9639
Epoch 4/20
368/368 [==============================] - 1s 4ms/step - loss: 0.0848 - accuracy: 0.9643
Epoch 5/20
368/368 [==============================] - 1s 3ms/step - loss: 0.0706 - accuracy: 0.9716
Epoch 6/20
368/368 [==============================] - 1s 4ms/step - loss: 0.0600 - accuracy: 0.9758
Epoch 7/20
368/368 [==============================] - 1s 4ms/step - loss: 0.0503 - accuracy: 0.9788
Epoch 8/20
368/368 [==============================] - 1s 4ms/step - loss: 0.0468 - accuracy: 0.9810
Epoch 9/20
368/368 [==============================] - 1s 4ms/step - loss: 0.0453 - accuracy: 0.9810
Epoch 10/20
368/368 [==============================] - 1s 4ms/step - loss: 0.0507 - accuracy: 0.9799
Epoch 11/2

In [8]:
import tensorflowjs as tfjs

tfjs.converters.save_keras_model(model_dep, 'Model_Depression_js')
tfjs.converters.save_keras_model(model_anx, 'Model_Anxiety_js')
tfjs.converters.save_keras_model(model_str, 'Model_Stress_js')

In [11]:
from matplotlib.pyplot import figure

figure(figsize = (8,6))
plt.plot(model_dep.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.show()

TypeError: 'History' object is not subscriptable

<Figure size 576x432 with 0 Axes>

In [18]:
depression_validation = pd.read_csv('data_valid_depr.csv')
anxiety_validation = pd.read_csv('data_valid_anx.csv')
stress_validation = pd.read_csv('data_valid_str.csv')

display(depression_validation, anxiety_validation, stress_validation)

Q3A  Q5A  Q10A  Q13A  Q16A  Q17A  Q21A  Q24A  Q26A  Q31A  Q34A  Q37A  \
0       3    3     3     2     3     3     3     3     3     3     3     3   
1       0    0     0     0     1     1     1     1     0     0     0     1   
2       1    1     2     1     1     1     1     1     2     1     2     1   
3       1    1     2     1     1     0     0     1     2     2     0     0   
4       2    2     2     3     2     1     2     3     2     1     3     0   
...   ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
4195    1    2     1     1     1     1     1     1     2     1     3     1   
4196    0    3     0     0     3     0     0     3     0     3     0     0   
4197    2    3     3     2     3     2     2     3     3     2     1     3   
4198    1    0     0     0     0     0     0     0     0     1     0     0   
4199    0    0     0     1     2     1     2     0     2     1     0     1   

      Q38A  Q42A  Extraverted-enthusiastic  Critical-quarrelsome  \
0        3     3                         6                     5   
1        1     1                         4                     5   
2        1     1                         4                     5   
3        0     2                         6                     3   
4        1     1                         4                     5   
...    ...   ...                       ...                   ...   
4195     1     2                         1                     4   
4196     0     3                         5                     5   
4197     2     3                         5                     5   
4198     0     1                         6                     1   
4199     0     1                         3                     2   

      Dependable-self_disciplined  Anxious-easily upset  \
0                               7                     5   
1                               6                     3   
2                               6                     6   
3                               5                     7   
4                               6                     5   
...                           ...                   ...   
4195                            7                     5   
4196                            1                     1   
4197                            1                     5   
4198                            3                     7   
4199                            7                     4   

      Open to new experiences-complex  Reserved-quiet  Sympathetic-warm  \
0                                   6               7                 7   
1                                   5               2                 4   
2                                   6               5                 5   
3                                   5               6                 7   
4                                   7               5                 6   
...                               ...             ...               ...   
4195                                5               7                 5   
4196                                7               3                 1   
4197                                6               5                 5   
4198                                4               2                 6   
4199                                7               3                 6   

      Disorganized-careless  Calm-emotionally_stable  Conventional-uncreative  \
0                         0                        1                        7   
1                         4                        3                        3   
2                         3                        2                        4   
3                         5                        2                        5   
4                         7                        4                        6   
...                     ...                      ...                      ...   
4195                      1                        4                       

Q2A  Q4A  Q7A  Q9A  Q15A  Q19A  Q20A  Q23A  Q25A  Q28A  Q30A  Q36A  \
0       0    1    3    3     3     3     2     1     1     3     0     2   
1       1    0    0    3     1     0     3     0     2     1     3     3   
2       0    0    1    0     1     0     1     1     0     1     2     1   
3       3    1    0    3     0     1     0     0     2     1     0     1   
4       1    1    0    1     1     1     1     0     2     1     2     1   
...   ...  ...  ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   
4195    0    3    3    3     1     1     3     3     2     3     3     3   
4196    1    0    2    3     1     3     0     0     3     0     2     0   
4197    1    0    0    1     0     0     0     0     1     0     0     1   
4198    1    1    0    1     0     0     1     1     0     0     0     0   
4199    0    0    1    1     1     0     2     0     1     1     2     2   

      Q40A  Q41A  Extraverted-enthusiastic  Critical-quarrelsome  \
0        3     1                         7                     4   
1        1     0                         3                     5   
2        0     0                         7                     4   
3        1     1                         2                     7   
4        0     1                         3                     5   
...    ...   ...                       ...                   ...   
4195     3     3                         6                     7   
4196     3     2                         1                     6   
4197     0     0                         5                     2   
4198     1     0                         4                     1   
4199     2     0                         4                     3   

      Dependable-self_disciplined  Anxious-easily upset  \
0                               5                     7   
1                               5                     4   
2                               4                     5   
3                               4                     5   
4                               5                     5   
...                           ...                   ...   
4195                            5                     7   
4196                            6                     7   
4197                            6                     5   
4198                            6                     5   
4199                            6                     6   

      Open to new experiences-complex  Reserved-quiet  Sympathetic-warm  \
0                                   7               5                 7   
1                                   6               7                 7   
2                                   6               5                 7   
3                                   6               5                 1   
4                                   6               5                 5   
...                               ...             ...               ...   
4195                                5               5                 5   
4196                                2               6                 3   
4197                                5               5                 6   
4198                                6               4                 1   
4199                                5               1                 4   

      Disorganized-careless  Calm-emotionally_stable  Conventional-uncreative  \
0                         5                        3                        1   
1                         4                        4                        7   
2                         4                        6                        5   
3                         6                        2                        1   
4                         3                        2                        3   
...                     ...                      ...                      ...   
4195                      7                        1                        2   
4196              

Q1A  Q6A  Q8A  Q11A  Q12A  Q14A  Q18A  Q22A  Q27A  Q29A  Q32A  Q33A  \
0       3    3    3     3     3     3     3     3     3     3     3     3   
1       0    0    1     1     1     0     0     1     0     0     0     2   
2       1    2    2     2     1     2     3     1     3     3     1     1   
3       2    3    0     3     3     1     2     3     3     3     1     3   
4       1    1    1     0     2     0     0     0     1     1     1     1   
...   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
4195    0    0    3     0     3     0     1     0     3     0     1     1   
4196    3    2    3     2     2     2     0     2     3     2     0     2   
4197    0    0    0     0     0     0     0     0     0     0     0     0   
4198    2    1    3     1     1     0     2     0     2     2     2     1   
4199    1    0    0     0     1     1     0     1     2     0     1     1   

      Q35A  Q39A  Extraverted-enthusiastic  Critical-quarrelsome  \
0        3     3                         2                     4   
1        0     0                         1                     1   
2        0     2                         6                     5   
3        3     3                         4                     5   
4        1     0                         4                     3   
...    ...   ...                       ...                   ...   
4195     3     0                         5                     1   
4196     1     3                         3                     5   
4197     0     0                         5                     5   
4198     2     1                         2                     2   
4199     1     0                         6                     6   

      Dependable-self_disciplined  Anxious-easily upset  \
0                               4                     7   
1                               7                     2   
2                               7                     6   
3                               3                     7   
4                               3                     5   
...                           ...                   ...   
4195                            5                     1   
4196                            2                     7   
4197                            7                     1   
4198                            3                     4   
4199                            5                     4   

      Open to new experiences-complex  Reserved-quiet  Sympathetic-warm  \
0                                   5               6                 6   
1                                   3               6                 7   
2                                   6               5                 5   
3                                   6               4                 5   
4                                   5               5                 4   
...                               ...             ...               ...   
4195                                7               4                 3   
4196                                5               7                 6   
4197                                5               6                 5   
4198                                5               7                 7   
4199                                4               1                 4   

      Disorganized-careless  Calm-emotionally_stable  Conventional-uncreative  \
0                         6                        2                        1   
1                         1                        6                        7   
2                         7                        5                        2   
3                         1                        5                        3   
4                         6                        6                        6   
...                     ...                      ...                      ...   
4195                      4                        7                        1   
4196  

In [19]:
index=2
X_hasil_depression = depression_validation.copy()
X_hasil_depression=X_hasil_depression = X_hasil_depression.iloc[:,0:54]#.values
X_hasil_depression=X_hasil_depression.loc[index].values
X_hasil_depression=np.array(X_hasil_depression).astype('float32').reshape((1,-1))
print(X_hasil_depression, depression_validation.loc[index,["Condition"]])

X_hasil_anxiety = anxiety_validation.copy()
X_hasil_anxiety=X_hasil_anxiety = X_hasil_anxiety.iloc[:,0:54]#.values
X_hasil_anxiety=X_hasil_anxiety.loc[index].values
X_hasil_anxiety=np.array(X_hasil_anxiety).astype('float32').reshape((1,-1))
print(X_hasil_anxiety, anxiety_validation.loc[index,["Condition"]])

X_hasil_stress = stress_validation.copy()
X_hasil_stress=X_hasil_stress = X_hasil_stress.iloc[:,0:54]#.values
X_hasil_stress=X_hasil_stress.loc[index].values
X_hasil_stress=np.array(X_hasil_stress).astype('float32').reshape((1,-1))
print(X_hasil_stress, stress_validation.loc[index,["Condition"]])

[[ 1.  1.  2.  1.  1.  1.  1.  1.  2.  1.  2.  1.  1.  1.  4.  5.  6.  6.
   6.  5.  5.  3.  2.  4.  1.  1.  0.  1.  1.  0.  0.  1.  0.  1.  0.  0.
   1.  1.  1.  1.  2.  3.  2.  1. 19.  2.  1.  8.  2. 10.  2.  1.  2.  2.]] Condition    1
Name: 2, dtype: int64
[[ 0.  0.  1.  0.  1.  0.  1.  1.  0.  1.  2.  1.  0.  0.  7.  4.  4.  5.
   6.  5.  7.  4.  6.  5.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  1.  3.  1.  2.  2. 21.  1.  2. 10.  1. 10.  2.  1.  4.  2.]] Condition    0
Name: 2, dtype: int64
[[ 1.  2.  2.  2.  1.  2.  3.  1.  3.  3.  1.  1.  0.  2.  6.  5.  7.  6.
   6.  5.  5.  7.  5.  2.  0.  1.  1.  0.  1.  0.  1.  0.  1.  1.  1.  0.
   1.  1.  0.  1.  2.  1.  2.  2. 20.  1.  1. 10.  0. 10.  2.  3.  2.  2.]] Condition    2
Name: 2, dtype: int64


In [20]:
hasil_akhir_depression = model.predict(X_hasil_depression)
hasil_akhir_anxiety = model.predict(X_hasil_anxiety)
hasil_akhir_stress = model.predict(X_hasil_stress)

print('Tingkat depresi: ',hasil_akhir_stress)
print('Tingkat depresi: ',np.argmax(hasil_akhir_depression))
print('Tingkat anxiety: ',np.argmax(hasil_akhir_anxiety))
print('Tingkat stress: ',np.argmax(hasil_akhir_stress))

1/1 [==============================] - 0s 34ms/step
Tingkat depresi:  [[0. 0. 1.]]
Tingkat depresi:  2
Tingkat anxiety:  2
Tingkat stress:  2
